---
- shell: "wget --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{jdk_url}} -O /tmp/java8.tar.gz"

- shell: tar -zxf /tmp/java8.tar.gz -C "{{jdk_install_path}}"

- shell: update-alternatives --install /usr/bin/java java "/opt/jdk/jdk{{jdk_version}}/bin/java" 100
  become: true
