---
- name: Download JDK
  changed_when: False
  shell: "wget --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{jdk_url}} -O /tmp/java.tar.gz"

- name: Extract JDK
  unarchive: src=/tmp/java.tar.gz dest="{{jdk_install_path}}" copy=no

- name: Select correct Java version
  alternatives: name=java path="/opt/jdk/jdk{{jdk_version}}/bin/java" link=/usr/bin/java
  become: true
